### ISSUE TITLE
Search LDAP exception

### ISSUE THREAD

**Issue by geoperez** [unosquare/swan#142]
System.ArgumentException: 'Destination array was not long enough. Check the destination index, length, and the array's lower bounds.'

   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Unosquare.Swan.Networking.Ldap.LdapConnection.RequestLdapMessage(LdapMessage msg, CancellationToken ct) in C:\Unosquare\swan\src\Unosquare.Swan\Networking\Ldap\LdapConnection.cs:line 516
   at Unosquare.Swan.Networking.Ldap.LdapConnection.Search(String base, Int32 scope, String filter, String[] attrs, Boolean typesOnly, CancellationToken ct) in C:\Unosquare\swan\src\Unosquare.Swan\Networking\Ldap\LdapConnection.cs:line 477
   at Unosquare.Swan.Samples.LdapSync.UpdateUsers(CancellationToken ct) in C:\Unosquare\swan\src\Unosquare.Swan.Samples\Program.cs:line 317
   at Unosquare.Swan.Samples.LdapSync.Sync(CancellationToken ct) in C:\Unosquare\swan\src\Unosquare.Swan.Samples\Program.cs:line 299
   at Unosquare.Swan.Samples.LdapSync.ProcessAsync(CancellationToken ct) in C:\Unosquare\swan\src\Unosquare.Swan.Samples\Program.cs:line 264
   at Unosquare.Swan.Samples.Program.Main(String[] args) in C:\Unosquare\swan\src\Unosquare.Swan.Samples\Program.cs:line 34
   at Unosquare.Swan.Samples.Program.<Main>(String[] args)

**Comment by geoperez** [comment]
It's really hard to reproduce...
