### ISSUE TITLE
Logger throws exception when redirecting stdout

### ISSUE THREAD

**Issue by Schnutzel** [unosquare/swan#247]
**Describe the bug**
When attempting to redirect a program's stdout, Logger throws an exception:
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Swan.Logging.Logger' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Swan.Terminal' threw an exception. ---> System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.Console.set_CursorVisible(Boolean value)
   at Swan.Terminal..cctor()
   --- End of inner exception stack trace ---
   at Swan.Terminal.get_IsConsolePresent()
   at Swan.Logging.Logger..cctor()
   --- End of inner exception stack trace ---
   at Swan.Logging.Logger.Log(String message, String source, LogLevel messageType, Object extendedData, String callerMemberName, String callerFilePath, Int32 callerLineNumber)
   at ConsoleApp1.Program.Main(String[] args) in 
```

**To Reproduce**
Create any program that uses Logging, for example:
```
using Swan.Logging;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Logger.Log("msg","src",LogLevel.Info);
        }
    }
}
```

Then redirect the program output to a file, e.g.
`ConsoleApp1.exe > output.txt`

**Expected behavior**
Program should exit normally.

**Desktop:**
 - OS: Windows 10
 - Version 3.1.0

**Comment by geoperez** [comment]
Interesting issue, let me review it
